
* Gold rush
** Tags
- shaken
** Ingredients
- 2 oz. bourbon
- 3/4 oz. honey syrup
- 3/8-1/2 oz. juice from fresh lemon
** Directions
Shake all ingredients well with ice. Strain into old fashioned glass with single large ice cube.
** Notes
- Honey syrup is made by combining 3 parts honey to 1 part water and mixing over medium heat until dissolved.
- The traditional recipe calls for 3/4 oz. lemon juice. I feel that this overpowers the drink.
- It's not recommended to try shaking with egg white, as in a sour. The honey syrup provides enough thickening and smoothing.

* Toronto
** Tags
- stirred
** Ingredients
- 2 oz. Canadian rye whiskey
- 1/4 oz. Fernet-Branca
- 3/8 oz. simple syrup
- 2 dashes Angostura bitters
*** Garnish
orange twist
** Directions
Stir all ingredients in a mixing glass with ice. Strain into a Coupe glass and garnish with an orange twist.
** Notes
- Original recipe calls for 1/4 oz. simple syrup, but using a little more helps to balance out the bitterness.

* New Toronto
** Tags
- stirred
** Ingredients
- 1 1/2 oz. bourbon
- 1/2 oz. sweet vermouth
- 1 tsp. Fernet-Branca
- 2 tsp. honey syrup
*** Garnish
lemon twist
** Directions
Combine ingredients in mixing glass and stir with ice until well-chilled. Strain into chilled glass and garnish with a lemon twist.
** Notes
A remix of the [[*Toronto][Toronto]].

* Un-smashed Maple Bourbon
** Tags
- built
** Ingredients
- 2 oz. bourbon
- 3/8 oz. lemon juice
- 3/8 oz. orange juice
- 1/2 oz. maple syrup
- 4 dashes Angostura bitters
*** Garnish
orange twist
** Directions
Mix all ingredients and pour over a large ice cube in an old-fashioned glass.
** Notes
- A personal modification of the [[https://www.foodandwine.com/recipes/maple-bourbon-smash][Maple-Bourbon Smash]]
- Perhaps this is a candidate for the addition of a pure acid? (citric, ascorbic, etc.)

* Sazerac
** Tags
- stirred
- winter
** Ingredients
- 2 oz. rye whiskey
- 1/4 oz. simple syrup
- 2 dashes Peychaud's bitters
- Absinthe to coat glass
*** Garnish
- lemon twist
** Directions
Swirl absinthe in a chilled glass to coat the inside thoroughly and dump excess. Pour remaining ingredients into a mixing tin with ice and stir until chilled. Strain mixture into the absinthe-coated glass and garnish with lemon twist.
** Notes
- Absinthe can be replaced with Herbsaint or an anisette like pastis.

* Negroni
** Tags
  - stirred
  - equal parts
** Ingredients
  - 1 oz. gin
  - 1 oz. Carpano Antica Formula vermouth
  - 1 oz. Campari
*** Garnish
orange twist
** Directions
  Stir all ingredients over ice and strain into a coupe glass.
   
* Negronino
** Tags
- stirred
** Ingredients
- 20 ml (3/4 oz.) Amaro Nonino
- 10 cl (3/8 oz.) Campari
- 25 ml (1 oz.) gin
- 25 ml (1 oz.) Carpano Antica Formula vermouth
*** Garnish
- grapefruit twist
** Directions
Stir all ingredients over ice and strain into a rocks glass with fresh ice.
** Notes
- Volumes in imperial units are scaled up
- If grapefruit isn't available, it can be replaced with orange (or possibly lemon).

* Last Word
** Tags
- shaken
- summer
** Ingredients
- 1 oz. gin
- 7/8 oz. lime juice
- 3/4 oz. Luxardo Maraschino
- 3/4 oz. green Chartreuse
** Directions
Combine ingredients in a shaker with ice and shake thoroughly. Strain into a coupe glass.
** Notes
The original recipe calls for equal parts of all ingredients. This modification is a little less sweet and a little stronger.

* Paper Plane
** Tags
- shaken
** Ingredients
- 3/4 oz. bourbon
- 3/4 oz. Aperol
- 3/4 oz. Amaro Nonino
- 3/4 oz. lemon juice
** Directions
Combine ingredients in a shaker with ice and shake until well-chilled, but do not over-shake or the result will be too watered down. Strain into a coupe glass.
** Notes
A darker remix of the [[*Last Word][Last Word]].
